packages:
  - packages/*
  - playground
  - docs

catalog:
  '@nuxt/fonts': ^0.14.0
  '@nuxt/ui': ^4.8.1
  '@tiptap/core': ^3.25.0
  '@tiptap/vue-3': ^3.25.0
  nanoid: ^5.1.11
  sharp: ^0.34.5
  zod: ^4.4.3

catalogMode: prefer

catalogs:
  cli:
    '@clack/prompts': ^1.5.1
    commander: ^15.0.0
    ejs: ^6.0.1
    picocolors: ^1.1.1
  core:
    '@iconify-json/lucide': ^1.2.111
    '@iconify-json/simple-icons': ^1.2.85
    '@libsql/client': ^0.17.3
    '@nuxt/a11y': 1.0.0-alpha.1
    '@nuxt/content': ^3.14.0
    '@nuxt/icon': ^2.2.3
    '@nuxt/kit': ^4.4.6
    '@nuxt/ui': ^4.8.1
    '@nuxtjs/i18n': ^10.4.0
    '@vueuse/core': ^14.3.0
    nuxt: ^4.4.6
    nuxt-studio: ^1.7.0
    tailwindcss: ^4.3.0
    zod: ^4.4.3
  dev:
    '@nuxt/schema': ^4.4.6
    '@types/ejs': ^3.1.5
    '@types/node': ^24.13.0
    '@vitest/coverage-v8': ^4.1.8
    bumpp: ^11.1.0
    changelogen: ^0.6.2
    changelogithub: ^14.0.0
    husky: ^9.1.7
    knip: ^6.15.0
    lint-staged: ^17.0.7
    oxfmt: ^0.53.0
    oxlint: ^1.68.0
    playwright: ^1.60.0
    tsdown: ^0.22.1
    typescript: ^6.0.3
    unpdf: ^1.6.2
    vitest: ^4.1.8
    vue-tsc: ^3.3.3
  docs:
    '@tailwindcss/vite': ^4.3.0
    vitepress: 2.0.0-alpha.17

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar
  - semver
  - undici-types
