/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.6.0_@nuxt+conten_ba96c3765dccf6167e4b176fc9e3cbfc/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.6.0_@nuxt+conten_ba96c3765dccf6167e4b176fc9e3cbfc/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UEditor: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.6.0_@nuxt+conten_ba96c3765dccf6167e4b176fc9e3cbfc/node_modules/@nuxt/ui/dist/runtime/components/Editor.vue')['default']
    UEditorDragHandle: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.6.0_@nuxt+conten_ba96c3765dccf6167e4b176fc9e3cbfc/node_modules/@nuxt/ui/dist/runtime/components/EditorDragHandle.vue')['default']
    UEditorSuggestionMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.6.0_@nuxt+conten_ba96c3765dccf6167e4b176fc9e3cbfc/node_modules/@nuxt/ui/dist/runtime/components/EditorSuggestionMenu.vue')['default']
    UEditorToolbar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.6.0_@nuxt+conten_ba96c3765dccf6167e4b176fc9e3cbfc/node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue')['default']
    UFileUpload: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.6.0_@nuxt+conten_ba96c3765dccf6167e4b176fc9e3cbfc/node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.6.0_@nuxt+conten_ba96c3765dccf6167e4b176fc9e3cbfc/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  }
}
