import { zipSync, strToU8 } from 'fflate'
import type { CapturedPage, CdpNetworkRecord } from '../types'
import { buildWacz, generateViewerHtml } from '../utils/wacz'

function sanitizeFilename(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

interface PageExportInfo {
  page: CapturedPage
  name: string
  hasStatic: boolean
  hasInteractive: boolean
}

function generateIndexHtml(entries: PageExportInfo[]): string {
  const rows = entries
    .map((entry) => {
      const staticLink = entry.hasStatic
        ? `<a href="static/${entry.name}.html" style="color:#2563EB;text-decoration:underline">Static</a>`
        : '<span style="color:#9CA3AF">-</span>'

      const interactiveLink = entry.hasInteractive
        ? `<a href="interactive/${entry.name}.html" style="color:#7C3AED;text-decoration:underline">Interactive</a>`
        : '<span style="color:#9CA3AF">-</span>'

      return `      <tr>
        <td style="padding:8px 12px;font-weight:500">${escapeHtml(entry.page.title)}</td>
        <td style="padding:8px 12px;color:#6B7280;font-size:0.875rem">${escapeHtml(entry.page.url)}</td>
        <td style="padding:8px 12px;text-align:center">${staticLink}</td>
        <td style="padding:8px 12px;text-align:center">${interactiveLink}</td>
      </tr>`
    })
    .join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FocusRing Web Share - Captured Pages</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 1024px; margin: 0 auto; padding: 2rem; color: #1F2937; }
    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
    .subtitle { color: #6B7280; margin-bottom: 2rem; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; padding: 8px 12px; border-bottom: 2px solid #E5E7EB; font-size: 0.875rem; color: #6B7280; text-transform: uppercase; letter-spacing: 0.05em; }
    tr:hover { background: #F9FAFB; }
    td { border-bottom: 1px solid #F3F4F6; }
    .info { margin-top: 2rem; padding: 1rem; background: #F0F9FF; border: 1px solid #BAE6FD; border-radius: 0.375rem; font-size: 0.875rem; color: #0C4A6E; }
    .warning { margin-top: 1rem; padding: 1rem; background: #FFFBEB; border: 1px solid #FDE68A; border-radius: 0.375rem; font-size: 0.875rem; color: #92400E; }
  </style>
</head>
<body>
  <h1>Captured Pages</h1>
  <p class="subtitle">Generated by FocusRing Web Share for WCAG accessibility auditing</p>
  <table>
    <thead>
      <tr>
        <th>Page</th>
        <th>Original URL</th>
        <th style="text-align:center">Static</th>
        <th style="text-align:center">Interactive</th>
      </tr>
    </thead>
    <tbody>
${rows}
    </tbody>
  </table>
  <div class="info">
    <strong>Static captures</strong> open directly in your browser as self-contained HTML files with all CSS, images, and fonts embedded. Use for quick visual inspection and CSS-based WCAG checks.
  </div>
  <div class="warning">
    <strong>Interactive captures</strong> preserve full JavaScript interactivity (forms, modals, keyboard navigation, ARIA). They require a local HTTP server to work. Run <code>npx serve .</code> in this directory and open the served URL.
  </div>
</body>
</html>`
}

function generateReadme(sessionName: string): string {
  return [
    `# FocusRing Web Share - ${sessionName}`,
    '',
    'This archive contains captured web pages for WCAG accessibility auditing.',
    'Each page is captured in two formats for comprehensive auditing.',
    '',
    '## How to use',
    '',
    '### Static captures (static/ folder)',
    '- Open any HTML file directly in your browser',
    '- Self-contained with all CSS, images, and fonts embedded',
    '- Best for: color contrast, text alternatives, semantic structure, focus styles',
    '',
    '### Interactive captures (interactive/ folder)',
    '- Require a local HTTP server (service workers need HTTP, not file://)',
    '- Run: `npx serve .` in this directory',
    '- Open the served URL in your browser',
    '- Full JavaScript interactivity preserved',
    '- Best for: keyboard navigation, ARIA state toggling, form validation, modals, focus management',
    '',
    '## Contents',
    '',
    '- `index.html` - Navigation page with links to all captured pages',
    '- `static/` - Static HTML captures (open directly)',
    '- `interactive/` - Interactive WACZ captures + viewer HTML (require HTTP server)',
    '',
    'Generated by [FocusRing Web Share](https://focusring.io)',
    ''
  ].join('\n')
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** Resolved data for a single page, ready for export (no callbacks) */
interface ExportPageData {
  page: CapturedPage
  html: string | undefined
  records: CdpNetworkRecord[] | undefined
}

/**
 * Build and download the export ZIP.
 * Takes pre-resolved data — no callbacks, to avoid Rolldown minifier
 * variable shadowing bugs with function parameters.
 */
async function doExportZip(
  pageDataList: ExportPageData[],
  sessionName: string,
  replayFiles: { sw: Uint8Array; ui: Uint8Array } | undefined
): Promise<void> {
  const zipFiles: Record<string, Uint8Array> = {}
  const indexEntries: PageExportInfo[] = []
  const usedNames = new Set<string>()

  // Process each page
  for (const data of pageDataList) {
    const pg = data.page

    if (pg.status !== 'captured') continue

    let safeName = sanitizeFilename(pg.title) || 'page'
    if (usedNames.has(safeName)) {
      safeName = `${safeName}-${pg.id}`
    }
    usedNames.add(safeName)

    let didStatic = false
    let didInteractive = false

    // Static HTML
    if (pg.staticCaptured && data.html) {
      zipFiles[`static/${safeName}.html`] = strToU8(data.html)
      didStatic = true
    }

    // Interactive WACZ
    if (pg.interactiveCaptured && data.records && data.records.length > 0) {
      try {
        const waczName = `${safeName}.wacz`
        const waczBytes = await buildWacz({
          records: data.records,
          pageUrl: pg.url,
          pageTitle: pg.title,
          captureDate: new Date(pg.addedAt).toISOString()
        })
        zipFiles[`interactive/${waczName}`] = waczBytes
        zipFiles[`interactive/${safeName}.html`] = strToU8(
          generateViewerHtml(waczName, pg.title, pg.url)
        )
        didInteractive = true
      } catch (error) {
        console.error('[export] WACZ build failed:', error)
      }
    }

    if (didStatic || didInteractive) {
      indexEntries.push({
        page: pg,
        name: safeName,
        hasStatic: didStatic,
        hasInteractive: didInteractive
      })
    }
  }

  if (indexEntries.length === 0) return

  // Include replayweb.page files for interactive captures
  if (replayFiles) {
    zipFiles['replay/sw.js'] = replayFiles.sw
    zipFiles['replay/ui.js'] = replayFiles.ui
  }

  zipFiles['index.html'] = strToU8(generateIndexHtml(indexEntries))
  zipFiles['README.md'] = strToU8(generateReadme(sessionName))

  const zipped = zipSync(zipFiles, { level: 6 })

  const blob = new Blob([zipped.buffer as ArrayBuffer], { type: 'application/zip' })
  const dlUrl = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = dlUrl
  anchor.download = `${sanitizeFilename(sessionName) || 'web-share'}-capture.zip`
  anchor.click()
  URL.revokeObjectURL(dlUrl)
}

function useExport() {
  function getTotalSize(pages: CapturedPage[]): string {
    const total = pages
      .filter((p) => p.status === 'captured')
      .reduce((sum, p) => sum + (p.staticSizeBytes ?? 0) + (p.interactiveSizeBytes ?? 0), 0)
    return formatSize(total)
  }

  return { getTotalSize, formatSize }
}

export { type ExportPageData, doExportZip, useExport }
