import { zipSync, strToU8 } from 'fflate'
import type { CapturedPage } from '../types'

function sanitizeFilename(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function generateIndexHtml(pages: CapturedPage[], filenames: Map<string, string>): string {
  const rows = pages
    .map((page) => {
      const filename = filenames.get(page.id) ?? 'page.html'
      const size = page.sizeBytes ? formatSize(page.sizeBytes) : '-'
      return `      <tr>
        <td style="padding:8px 12px"><a href="pages/${filename}" style="color:#2563eb;text-decoration:underline">${escapeHtml(page.title)}</a></td>
        <td style="padding:8px 12px;color:#6b7280;font-size:0.875rem">${escapeHtml(page.url)}</td>
        <td style="padding:8px 12px;color:#6b7280;font-size:0.875rem;text-align:right">${size}</td>
      </tr>`
    })
    .join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FocusRing Web Share - Captured Pages</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 960px; margin: 0 auto; padding: 2rem; color: #1f2937; }
    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
    .subtitle { color: #6b7280; margin-bottom: 2rem; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; padding: 8px 12px; border-bottom: 2px solid #e5e7eb; font-size: 0.875rem; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }
    th:last-child { text-align: right; }
    tr:hover { background: #f9fafb; }
    td { border-bottom: 1px solid #f3f4f6; }
    .info { margin-top: 2rem; padding: 1rem; background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 0.375rem; font-size: 0.875rem; color: #0c4a6e; }
  </style>
</head>
<body>
  <h1>Captured Pages</h1>
  <p class="subtitle">Generated by FocusRing Web Share for WCAG accessibility auditing</p>
  <table>
    <thead>
      <tr>
        <th>Page</th>
        <th>Original URL</th>
        <th>Size</th>
      </tr>
    </thead>
    <tbody>
${rows}
    </tbody>
  </table>
  <div class="info">
    <strong>How to use:</strong> Click any page link above to open the captured version. Each page is self-contained with all CSS, images, and fonts embedded. Use your browser's developer tools, screen readers, and keyboard navigation to perform your WCAG audit.
  </div>
</body>
</html>`
}

function generateReadme(sessionName: string): string {
  return `# FocusRing Web Share - ${sessionName}

This archive contains captured web pages for WCAG accessibility auditing.

## How to use

1. Open \`index.html\` in your browser
2. Click on any page to open the captured version
3. Each page is self-contained (CSS, images, fonts are embedded)
4. Use browser DevTools, screen readers, and keyboard navigation for your audit

## Contents

- \`index.html\` - Navigation page with links to all captured pages
- \`pages/\` - Directory containing all captured HTML pages

## Notes

- Pages were captured using SingleFile technology
- JavaScript may have limited functionality in captured pages
- All CSS, images, and fonts are inlined for offline use
- Original URLs are preserved as reference

Generated by [FocusRing Web Share](https://focusring.io)
`
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function useExport() {
  function exportZip(
    pages: CapturedPage[],
    sessionName: string,
    getHtml: (id: string) => string | undefined
  ): void {
    const captured = pages.filter((p) => p.status === 'captured')
    if (captured.length === 0) return

    const files: Record<string, Uint8Array> = {}
    const filenames = new Map<string, string>()
    const usedNames = new Set<string>()

    for (const page of captured) {
      const html = getHtml(page.id)
      if (!html) continue

      let name = sanitizeFilename(page.title) || 'page'
      if (usedNames.has(name)) {
        name = `${name}-${page.id}`
      }
      usedNames.add(name)

      const filename = `${name}.html`
      filenames.set(page.id, filename)
      files[`pages/${filename}`] = strToU8(html)
    }

    files['index.html'] = strToU8(generateIndexHtml(captured, filenames))
    files['README.md'] = strToU8(generateReadme(sessionName))

    const zipped = zipSync(files, { level: 6 })

    const blob = new Blob([zipped.buffer as ArrayBuffer], { type: 'application/zip' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${sanitizeFilename(sessionName) || 'web-share'}-capture.zip`
    a.click()
    URL.revokeObjectURL(url)
  }

  function getTotalSize(pages: CapturedPage[]): string {
    const total = pages
      .filter((p) => p.status === 'captured')
      .reduce((sum, p) => sum + (p.sizeBytes ?? 0), 0)
    return formatSize(total)
  }

  return { exportZip, getTotalSize, formatSize }
}
