import { type ChildProcess } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'

import {
  cleanupProject,
  installDependencies,
  packWcagify,
  patchPackageJsonForLocalWcagify,
  scaffoldProject,
  startDevServer,
  stopDevServer
} from './setup/test-utils.js'

const PROJECT_NAME = 'upload-test'

/** Valid 1x1 PNG generated by sharp. */
function makeValidPng(): Buffer {
  return Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGP4z8DwHwAFAAH/iZk9HQAAAABJRU5ErkJggg==',
    'base64'
  )
}

/** Minimal valid 1x1 JPEG. */
function makeValidJpeg(): Buffer {
  return Buffer.from(
    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AKwA//9k=',
    'base64'
  )
}

/** Minimal valid 1x1 GIF89a. */
function makeValidGif(): Buffer {
  return Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7', 'base64')
}

/** Build a multipart/form-data body with a single file field. */
function buildMultipartBody(
  file: Buffer,
  filename: string,
  contentType: string
): { body: Buffer; boundary: string } {
  const boundary = '----WebKitFormBoundary' + Math.random().toString(36).slice(2)
  const parts = [
    `--${boundary}\r\n`,
    `Content-Disposition: form-data; name="file"; filename="${filename}"\r\n`,
    `Content-Type: ${contentType}\r\n\r\n`
  ]
  const header = Buffer.from(parts.join(''))
  const footer = Buffer.from(`\r\n--${boundary}--\r\n`)
  return { body: Buffer.concat([header, file, footer]), boundary }
}

describe('Image upload E2E', () => {
  let devServerProcess: ChildProcess
  let baseUrl: string
  let projectPath: string

  beforeAll(async () => {
    cleanupProject(PROJECT_NAME)
    projectPath = scaffoldProject(PROJECT_NAME)
    const tarball = packWcagify()
    patchPackageJsonForLocalWcagify(projectPath, tarball)
    installDependencies(projectPath)

    const server = await startDevServer(projectPath, 3103)
    devServerProcess = server.process
    baseUrl = server.url
  }, 300_000)

  afterAll(() => {
    if (devServerProcess) stopDevServer(devServerProcess)
  })

  describe('POST /api/issues/upload', () => {
    it('accepts a valid PNG and returns a WebP URL', async () => {
      const png = makeValidPng()
      const { body, boundary } = buildMultipartBody(png, 'test.png', 'image/png')

      const res = await fetch(`${baseUrl}/api/issues/upload`, {
        method: 'POST',
        headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
        body
      })

      expect(res.status).toBe(200)
      const json = await res.json()
      expect(json.url).toMatch(/^\/api\/uploads\/[a-f0-9-]+\.webp$/)
    })

    it('accepts a valid JPEG and returns a WebP URL', async () => {
      const jpeg = makeValidJpeg()
      const { body, boundary } = buildMultipartBody(jpeg, 'photo.jpg', 'image/jpeg')

      const res = await fetch(`${baseUrl}/api/issues/upload`, {
        method: 'POST',
        headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
        body
      })

      expect(res.status).toBe(200)
      const json = await res.json()
      expect(json.url).toMatch(/^\/api\/uploads\/[a-f0-9-]+\.webp$/)
    })

    it('accepts a valid GIF and returns a WebP URL', async () => {
      const gif = makeValidGif()
      const { body, boundary } = buildMultipartBody(gif, 'anim.gif', 'image/gif')

      const res = await fetch(`${baseUrl}/api/issues/upload`, {
        method: 'POST',
        headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
        body
      })

      expect(res.status).toBe(200)
      const json = await res.json()
      expect(json.url).toMatch(/^\/api\/uploads\/[a-f0-9-]+\.webp$/)
    })

    it('serves the uploaded image back as WebP', async () => {
      const png = makeValidPng()
      const { body, boundary } = buildMultipartBody(png, 'retrieve.png', 'image/png')

      const uploadRes = await fetch(`${baseUrl}/api/issues/upload`, {
        method: 'POST',
        headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
        body
      })
      const { url } = await uploadRes.json()

      const imageRes = await fetch(`${baseUrl}${url}`)
      expect(imageRes.status).toBe(200)
      expect(imageRes.headers.get('content-type')).toBe('image/webp')
      expect(imageRes.headers.get('cache-control')).toContain('immutable')

      const imageData = await imageRes.arrayBuffer()
      expect(imageData.byteLength).toBeGreaterThan(0)
    })

    it('rejects a disallowed MIME type', async () => {
      const textData = Buffer.from('not an image')
      const { body, boundary } = buildMultipartBody(textData, 'hack.txt', 'text/plain')

      const res = await fetch(`${baseUrl}/api/issues/upload`, {
        method: 'POST',
        headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
        body
      })

      expect(res.status).toBe(400)
      const text = await res.text()
      expect(text).toContain('not allowed')
    })

    it('rejects a file exceeding 2MB', async () => {
      // Create a valid PNG header followed by enough padding to exceed 2MB
      const png = makeValidPng()
      const oversized = Buffer.alloc(2 * 1024 * 1024 + 1)
      png.copy(oversized)

      const { body, boundary } = buildMultipartBody(oversized, 'huge.png', 'image/png')

      const res = await fetch(`${baseUrl}/api/issues/upload`, {
        method: 'POST',
        headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
        body
      })

      expect(res.status).toBe(400)
      const text = await res.text()
      expect(text).toContain('2MB')
    })

    it('rejects spoofed magic bytes (text file claimed as PNG)', async () => {
      const fake = Buffer.from('This is definitely not a PNG image file contents')
      const { body, boundary } = buildMultipartBody(fake, 'fake.png', 'image/png')

      const res = await fetch(`${baseUrl}/api/issues/upload`, {
        method: 'POST',
        headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
        body
      })

      expect(res.status).toBe(400)
      const text = await res.text()
      expect(text).toContain('does not match')
    })

    it('rejects spoofed magic bytes (JPEG header claimed as PNG)', async () => {
      const jpeg = makeValidJpeg()
      const { body, boundary } = buildMultipartBody(jpeg, 'sneaky.png', 'image/png')

      const res = await fetch(`${baseUrl}/api/issues/upload`, {
        method: 'POST',
        headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
        body
      })

      expect(res.status).toBe(400)
      const text = await res.text()
      expect(text).toContain('does not match')
    })

    it('rejects a request with no file field', async () => {
      const boundary = '----WebKitFormBoundary' + Math.random().toString(36).slice(2)
      const body = Buffer.from(
        `--${boundary}\r\nContent-Disposition: form-data; name="other"\r\n\r\nsome value\r\n--${boundary}--\r\n`
      )

      const res = await fetch(`${baseUrl}/api/issues/upload`, {
        method: 'POST',
        headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
        body
      })

      expect(res.status).toBe(400)
    })
  })

  describe('GET /api/uploads/[filename]', () => {
    it('rejects path traversal in filename', async () => {
      const res = await fetch(`${baseUrl}/api/uploads/../../../etc/passwd`)
      expect(res.ok).toBe(false)
    })

    it('rejects filenames with unsafe characters', async () => {
      const res = await fetch(`${baseUrl}/api/uploads/evil<script>.webp`)
      expect(res.ok).toBe(false)
    })

    it('returns 404 for non-existent file', async () => {
      const res = await fetch(`${baseUrl}/api/uploads/00000000-0000-0000-0000-000000000000.webp`)
      expect(res.status).toBe(404)
    })
  })

  describe('image relocation on issue creation', () => {
    it('moves uploaded images to report folder and rewrites URLs', async () => {
      // Step 1: Upload an image
      const png = makeValidPng()
      const { body, boundary } = buildMultipartBody(png, 'relocate.png', 'image/png')

      const uploadRes = await fetch(`${baseUrl}/api/issues/upload`, {
        method: 'POST',
        headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
        body
      })
      const { url: tempUrl } = await uploadRes.json()
      expect(tempUrl).toMatch(/^\/api\/uploads\/[a-f0-9-]+\.webp$/)

      // Step 2: Get a valid report slug and sample ID
      const reportsRes = await fetch(`${baseUrl}/api/reports`)
      const reports = await reportsRes.json()
      const report = reports[0]
      const reportSlug = report.slug
      const sampleId = report.sample[0]?.id ?? 'homepage'

      // Step 3: Create an issue with a description referencing the uploaded image
      const description = `Screenshot of the issue:\n\n![screenshot](${tempUrl})`
      const issueRes = await fetch(`${baseUrl}/api/issues`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          report: reportSlug,
          title: 'Upload relocation test',
          sc: '1.4.3',
          severity: 'Medium',
          sample: sampleId,
          description
        })
      })

      expect(issueRes.status).toBe(200)
      const issueResult = await issueRes.json()
      expect(issueResult.success).toBe(true)

      // Step 4: The original temp URL should no longer serve the image (moved)
      const oldRes = await fetch(`${baseUrl}${tempUrl}`)
      expect(oldRes.status).toBe(404)

      // Step 5: Read the created markdown file from disk and verify the image path
      const issueFilePath = issueResult.path
      const mdContent = readFileSync(join(projectPath, issueFilePath), 'utf-8')

      // The markdown should NOT contain the old temp upload URL
      expect(mdContent).not.toContain(tempUrl)

      // The markdown should contain a relocated image path under the report slug
      const relocatedUrlPattern = new RegExp(`\\/api\\/uploads\\/${reportSlug}\\/[a-z0-9-]+\\.webp`)
      expect(mdContent).toMatch(relocatedUrlPattern)

      // Extract the relocated URL and verify the image is served correctly
      const match = mdContent.match(relocatedUrlPattern)
      expect(match).not.toBeNull()
      const relocatedRes = await fetch(`${baseUrl}${match![0]}`)
      expect(relocatedRes.status).toBe(200)
      expect(relocatedRes.headers.get('content-type')).toBe('image/webp')
    })
  })
})
